WELL= ../../../well
WFLAGS= -i -cc "-framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL -Llib/mac -lraylib"

all:
	$(WELL) main.well $(WFLAGS)

clean:
	rm *.o *.s a.out
